# Generated by Django 4.2.3 on 2023-11-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_member_project_services_url_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
