# Generated by Django 4.2.3 on 2023-11-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_part_file_part_project_part_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
